packages: []
catalogs:
  build:
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.4.1
    '@nuxt/kit': ^3.17.6
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.1
    '@tailwindcss/vite': ^4.1.11
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.4.0
    nuxt: ^3.17.6
    shadcn-nuxt: ^2.2.0
    tailwindcss: ^4.1.11
    unplugin: ^2.3.5
    unplugin-icons: ^22.1.0
    vite: ^7.0.0
  dev:
    '@antfu/eslint-config': ^4.16.1
    eslint: ^9.30.1
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^3.0.0
  frontend:
    '@vueuse/core': ^13.4.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-vue-next: ^0.525.0
    pinia: ^3.0.3
    reka-ui: ^2.3.2
    tailwind-merge: ^3.3.1
    tw-animate-css: ^1.3.5
    vue: ^3.5.17
  icons:
    '@iconify/json': ^2.2.356

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
